-- Fix: Add missing ES_BORRADO columns and fix column types
-- Run this on your existing gym_universitario database

-- Add ES_BORRADO to ASISTENCIA
ALTER TABLE `asistencia` ADD COLUMN `ES_BORRADO` TINYINT(1) DEFAULT 0;

-- Add ES_BORRADO to MEMBRESIA
ALTER TABLE `membresia` ADD COLUMN `ES_BORRADO` TINYINT(1) DEFAULT 0;

-- Add ES_BORRADO to PAGO
ALTER TABLE `pago` ADD COLUMN `ES_BORRADO` TINYINT(1) DEFAULT 0;

-- Fix CODIGO_MEMBRESIA in ASISTENCIA to VARCHAR(50)
ALTER TABLE `asistencia` MODIFY COLUMN `CODIGO_MEMBRESIA` VARCHAR(50) NOT NULL;

-- Fix CODIGO_MEMBRESIA in PAGO to VARCHAR(50)
ALTER TABLE `pago` MODIFY COLUMN `CODIGO_MEMBRESIA` VARCHAR(50) NOT NULL;

-- Fix CODIGO_MEMBRESIA in MEMBRESIA to VARCHAR(50) AUTO_INCREMENT compatible
ALTER TABLE `membresia` MODIFY COLUMN `CODIGO_MEMBRESIA` INT(11) NOT NULL AUTO_INCREMENT;
