-- Migration: Add MEMBRESIA, PAGO, and ASISTENCIA tables
-- Database: gym_universitario
-- Date: 2026-05-11

-- Table: MEMBRESIA
CREATE TABLE IF NOT EXISTS MEMBRESIA (
    CODIGO_MEMBRESIA VARCHAR(50) PRIMARY KEY,
    CI_CLIENTE VARCHAR(20) NOT NULL,
    ID_PLAN INT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    DIAS_ASIGNADOS INT NOT NULL,
    DIAS_DISPONIBLES INT NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ES_BORRADO TINYINT(1) DEFAULT 0,
    FOREIGN KEY (CI_CLIENTE) REFERENCES USUARIO(CI) ON DELETE CASCADE,
    FOREIGN KEY (ID_PLAN) REFERENCES PLAN(ID_PLAN) ON DELETE CASCADE,
    INDEX idx_ci_cliente (CI_CLIENTE),
    INDEX idx_fecha_fin (FECHA_FIN),
    INDEX idx_es_borrado (ES_BORRADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: PAGO
CREATE TABLE IF NOT EXISTS PAGO (
    ID_RECIBO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_MEMBRESIA VARCHAR(50) NOT NULL,
    CI_ADMINISTRADOR VARCHAR(20) DEFAULT NULL,
    CI_CLIENTE VARCHAR(20) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MONTO DECIMAL(10,2) NOT NULL,
    CODIGO_PAGO VARCHAR(100) DEFAULT NULL,
    TIPO_PAGO ENUM('QR', 'EFECTIVO') NOT NULL,
    NRO_DOCUMENTO VARCHAR(100) DEFAULT NULL,
    ES_BORRADO TINYINT(1) DEFAULT 0,
    FOREIGN KEY (CODIGO_MEMBRESIA) REFERENCES MEMBRESIA(CODIGO_MEMBRESIA) ON DELETE CASCADE,
    FOREIGN KEY (CI_ADMINISTRADOR) REFERENCES USUARIO(CI) ON DELETE SET NULL,
    FOREIGN KEY (CI_CLIENTE) REFERENCES USUARIO(CI) ON DELETE CASCADE,
    INDEX idx_codigo_membresia (CODIGO_MEMBRESIA),
    INDEX idx_ci_cliente (CI_CLIENTE),
    INDEX idx_fecha (FECHA),
    INDEX idx_es_borrado (ES_BORRADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: ASISTENCIA
CREATE TABLE IF NOT EXISTS ASISTENCIA (
    ID_ASISTENCIA INT AUTO_INCREMENT PRIMARY KEY,
    CI_CLIENTE VARCHAR(20) NOT NULL,
    ID_BIOMETRICO INT NOT NULL,
    CODIGO_MEMBRESIA VARCHAR(50) NOT NULL,
    FECHA_DE_INGRESO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ES_BORRADO TINYINT(1) DEFAULT 0,
    FOREIGN KEY (CI_CLIENTE) REFERENCES USUARIO(CI) ON DELETE CASCADE,
    FOREIGN KEY (CODIGO_MEMBRESIA) REFERENCES MEMBRESIA(CODIGO_MEMBRESIA) ON DELETE CASCADE,
    INDEX idx_ci_cliente (CI_CLIENTE),
    INDEX idx_fecha_ingreso (FECHA_DE_INGRESO),
    INDEX idx_codigo_membresia (CODIGO_MEMBRESIA),
    INDEX idx_es_borrado (ES_BORRADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add HUELLA column to USUARIO if not exists (it should already exist but just in case)
-- ALTER TABLE USUARIO ADD COLUMN IF NOT EXISTS HUELLA TINYINT(1) DEFAULT 0;
-- ALTER TABLE USUARIO ADD COLUMN IF NOT EXISTS ES_BORRADO TINYINT(1) DEFAULT 0;
